# Site settings
title: Darah Sunda
description: 'Aan Nuraini. Gadis keturunan sunda yang lahir di tanah melayu Indragiri Hulu '
url: 'http://aanuraini3.github.io'
baseurl: '/aannuraini3.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Aan Nuraini'
  email: aannuraini628@yahoo.co.id
  twitter_username: aannur_aini
  facebook_username: Aan Nuraini
  github_username:  aannuraini3
  linkedin_username:https://www.linkedin.com/in/aan-nuraini-80a672118?trk=nav_responsive_tab_profile_pic
  
  # Site owner 
  owner:  
  name: Aan Nuraini   
  avatar: bio-photo.jpg   
  bio: "Aan Nuraini. Gadis keturunan sunda yang lahir di tanah melayu Indragiri Hulu." 

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
